import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/custom/Footer";
import Navbar from "@/components/custom/Navbar";
import Script from "next/script";
import AdComponent from "@/components/custom/AdComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <AdComponent />
      </head>
      <body className={inter.className}>
        <main>
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
